# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\x12\ncalculator\">\n\x12\x43\x61lculationRequest\x12\x0b\n\x03op1\x18\x01 \x01(\x05\x12\x0b\n\x03op2\x18\x02 \x01(\x05\x12\x0e\n\x06\x63hoice\x18\x03 \x01(\t\"%\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3'
)




_CALCULATIONREQUEST = _descriptor.Descriptor(
  name='CalculationRequest',
  full_name='calculator.CalculationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op1', full_name='calculator.CalculationRequest.op1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op2', full_name='calculator.CalculationRequest.op2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='choice', full_name='calculator.CalculationRequest.choice', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=94,
)


_CALCULATIONRESPONSE = _descriptor.Descriptor(
  name='CalculationResponse',
  full_name='calculator.CalculationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.CalculationResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['CalculationRequest'] = _CALCULATIONREQUEST
DESCRIPTOR.message_types_by_name['CalculationResponse'] = _CALCULATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculationRequest = _reflection.GeneratedProtocolMessageType('CalculationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculationRequest)
  })
_sym_db.RegisterMessage(CalculationRequest)

CalculationResponse = _reflection.GeneratedProtocolMessageType('CalculationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculationResponse)
  })
_sym_db.RegisterMessage(CalculationResponse)


# @@protoc_insertion_point(module_scope)
